<a href="https://colab.research.google.com/github/sharanya1234567/Sharanya-Vemula/blob/main/Python_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%pip install pandas
%pip install scipy

In [ ]:
import pandas as pd
df = pd.read_csv("loan_data.csv")
df.head()

credit.policy             purpose  int.rate  installment  log.annual.inc  \
0              1  debt_consolidation    0.1189       829.10       11.350407   
1              1         credit_card    0.1071       228.22       11.082143   
2              1  debt_consolidation    0.1357       366.86       10.373491   
3              1  debt_consolidation    0.1008       162.34       11.350407   
4              1         credit_card    0.1426       102.92       11.299732   

     dti  fico  days.with.cr.line  revol.bal  revol.util  inq.last.6mths  \
0  19.48   737        5639.958333      28854        52.1               0   
1  14.29   707        2760.000000      33623        76.7               0   
2  11.63   682        4710.000000       3511        25.6               1   
3   8.10   712        2699.958333      33667        73.2               1   
4  14.97   667        4066.000000       4740        39.5               0   

   delinq.2yrs  pub.rec  not.fully.paid  
0            0        0               0  
1            0        0               0  
2            0        0               0  
3            0        0               0  
4            1        0               0

In [ ]:
df.isnull()


credit.policy  purpose  int.rate  installment  log.annual.inc    dti  \
0             False    False     False        False           False  False   
1             False    False     False        False           False  False   
2             False    False     False        False           False  False   
3             False    False     False        False           False  False   
4             False    False     False        False           False  False   
...             ...      ...       ...          ...             ...    ...   
9573          False    False     False        False           False  False   
9574          False    False     False        False           False  False   
9575          False    False     False        False           False  False   
9576          False    False     False        False           False  False   
9577          False    False     False        False           False  False   

       fico  days.with.cr.line  revol.bal  revol.util  inq.last.6mths  \
0     False              False      False       False           False   
1     False              False      False       False           False   
2     False              False      False       False           False   
3     False              False      False       False           False   
4     False              False      False       False           False   
...     ...                ...        ...         ...             ...   
9573  False              False      False       False           False   
9574  False              False      False       False           False   
9575  False              False      False       False           False   
9576  False              False      False       False           False   
9577  False              False      False       False           False   

      delinq.2yrs  pub.rec  not.fully.paid  
0           False    False           False  
1           False    False           False  
2           False    False           False  
3           False    False           False  
4           False    False           False  
...           ...      ...             ...  
9573        False    False           False  
9574        False    False           False  
9575        False    False           False  
9576        False    False           False  
9577        False    False           False  

[9578 rows x 14 columns]

In [ ]:
df.isnull().sum()

credit.policy        0
purpose              0
int.rate             0
installment          0
log.annual.inc       0
dti                  0
fico                 0
days.with.cr.line    0
revol.bal            0
revol.util           0
inq.last.6mths       0
delinq.2yrs          0
pub.rec              0
not.fully.paid       0
dtype: int64

In [ ]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9578 entries, 0 to 9577
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   credit.policy      9578 non-null   int64  
 1   purpose            9578 non-null   object 
 2   int.rate           9578 non-null   float64
 3   installment        9578 non-null   float64
 4   log.annual.inc     9578 non-null   float64
 5   dti                9578 non-null   float64
 6   fico               9578 non-null   int64  
 7   days.with.cr.line  9578 non-null   float64
 8   revol.bal          9578 non-null   int64  
 9   revol.util         9578 non-null   float64
 10  inq.last.6mths     9578 non-null   int64  
 11  delinq.2yrs        9578 non-null   int64  
 12  pub.rec            9578 non-null   int64  
 13  not.fully.paid     9578 non-null   int64  
dtypes: float64(6), int64(7), object(1)
memory usage: 1.0+ MB


In [ ]:
df2 = df.fillna(value = 0)
df2.head()

credit.policy             purpose  int.rate  installment  log.annual.inc  \
0              1  debt_consolidation    0.1189       829.10       11.350407   
1              1         credit_card    0.1071       228.22       11.082143   
2              1  debt_consolidation    0.1357       366.86       10.373491   
3              1  debt_consolidation    0.1008       162.34       11.350407   
4              1         credit_card    0.1426       102.92       11.299732   

     dti  fico  days.with.cr.line  revol.bal  revol.util  inq.last.6mths  \
0  19.48   737        5639.958333      28854        52.1               0   
1  14.29   707        2760.000000      33623        76.7               0   
2  11.63   682        4710.000000       3511        25.6               1   
3   8.10   712        2699.958333      33667        73.2               1   
4  14.97   667        4066.000000       4740        39.5               0   

   delinq.2yrs  pub.rec  not.fully.paid  
0            0        0               0  
1            0        0               0  
2            0        0               0  
3            0        0               0  
4            1        0               0

In [ ]:
df3 = df.fillna(method='pad')
df3.head()

credit.policy             purpose  int.rate  installment  log.annual.inc  \
0              1  debt_consolidation    0.1189       829.10       11.350407   
1              1         credit_card    0.1071       228.22       11.082143   
2              1  debt_consolidation    0.1357       366.86       10.373491   
3              1  debt_consolidation    0.1008       162.34       11.350407   
4              1         credit_card    0.1426       102.92       11.299732   

     dti  fico  days.with.cr.line  revol.bal  revol.util  inq.last.6mths  \
0  19.48   737        5639.958333      28854        52.1               0   
1  14.29   707        2760.000000      33623        76.7               0   
2  11.63   682        4710.000000       3511        25.6               1   
3   8.10   712        2699.958333      33667        73.2               1   
4  14.97   667        4066.000000       4740        39.5               0   

   delinq.2yrs  pub.rec  not.fully.paid  
0            0        0               0  
1            0        0               0  
2            0        0               0  
3            0        0               0  
4            1        0               0

In [ ]:
df4 = df.fillna(value=df['installment'].mean())
df4

credit.policy             purpose  int.rate  installment  \
0                 1  debt_consolidation    0.1189       829.10   
1                 1         credit_card    0.1071       228.22   
2                 1  debt_consolidation    0.1357       366.86   
3                 1  debt_consolidation    0.1008       162.34   
4                 1         credit_card    0.1426       102.92   
...             ...                 ...       ...          ...   
9573              0           all_other    0.1461       344.76   
9574              0           all_other    0.1253       257.70   
9575              0  debt_consolidation    0.1071        97.81   
9576              0    home_improvement    0.1600       351.58   
9577              0  debt_consolidation    0.1392       853.43   

      log.annual.inc    dti  fico  days.with.cr.line  revol.bal  revol.util  \
0          11.350407  19.48   737        5639.958333      28854        52.1   
1          11.082143  14.29   707        2760.000000      33623        76.7   
2          10.373491  11.63   682        4710.000000       3511        25.6   
3          11.350407   8.10   712        2699.958333      33667        73.2   
4          11.299732  14.97   667        4066.000000       4740        39.5   
...              ...    ...   ...                ...        ...         ...   
9573       12.180755  10.39   672       10474.000000     215372        82.1   
9574       11.141862   0.21   722        4380.000000        184         1.1   
9575       10.596635  13.09   687        3450.041667      10036        82.9   
9576       10.819778  19.18   692        1800.000000          0         3.2   
9577       11.264464  16.28   732        4740.000000      37879        57.0   

      inq.last.6mths  delinq.2yrs  pub.rec  not.fully.paid  
0                  0            0        0               0  
1                  0            0        0               0  
2                  1            0        0               0  
3                  1            0        0               0  
4                  0            1        0               0  
...              ...          ...      ...             ...  
9573               2            0        0               1  
9574               5            0        0               1  
9575               8            0        0               1  
9576               5            0        0               1  
9577               6            0        0               1  

[9578 rows x 14 columns]

In [ ]:
df5 = df.dropna()
df5

credit.policy             purpose  int.rate  installment  \
0                 1  debt_consolidation    0.1189       829.10   
1                 1         credit_card    0.1071       228.22   
2                 1  debt_consolidation    0.1357       366.86   
3                 1  debt_consolidation    0.1008       162.34   
4                 1         credit_card    0.1426       102.92   
...             ...                 ...       ...          ...   
9573              0           all_other    0.1461       344.76   
9574              0           all_other    0.1253       257.70   
9575              0  debt_consolidation    0.1071        97.81   
9576              0    home_improvement    0.1600       351.58   
9577              0  debt_consolidation    0.1392       853.43   

      log.annual.inc    dti  fico  days.with.cr.line  revol.bal  revol.util  \
0          11.350407  19.48   737        5639.958333      28854        52.1   
1          11.082143  14.29   707        2760.000000      33623        76.7   
2          10.373491  11.63   682        4710.000000       3511        25.6   
3          11.350407   8.10   712        2699.958333      33667        73.2   
4          11.299732  14.97   667        4066.000000       4740        39.5   
...              ...    ...   ...                ...        ...         ...   
9573       12.180755  10.39   672       10474.000000     215372        82.1   
9574       11.141862   0.21   722        4380.000000        184         1.1   
9575       10.596635  13.09   687        3450.041667      10036        82.9   
9576       10.819778  19.18   692        1800.000000          0         3.2   
9577       11.264464  16.28   732        4740.000000      37879        57.0   

      inq.last.6mths  delinq.2yrs  pub.rec  not.fully.paid  
0                  0            0        0               0  
1                  0            0        0               0  
2                  1            0        0               0  
3                  1            0        0               0  
4                  0            1        0               0  
...              ...          ...      ...             ...  
9573               2            0        0               1  
9574               5            0        0               1  
9575               8            0        0               1  
9576               5            0        0               1  
9577               6            0        0               1  

[9578 rows x 14 columns]

In [ ]:
df6 = df.interpolate(method = 'linear')
df6

credit.policy             purpose  int.rate  installment  \
0                 1  debt_consolidation    0.1189       829.10   
1                 1         credit_card    0.1071       228.22   
2                 1  debt_consolidation    0.1357       366.86   
3                 1  debt_consolidation    0.1008       162.34   
4                 1         credit_card    0.1426       102.92   
...             ...                 ...       ...          ...   
9573              0           all_other    0.1461       344.76   
9574              0           all_other    0.1253       257.70   
9575              0  debt_consolidation    0.1071        97.81   
9576              0    home_improvement    0.1600       351.58   
9577              0  debt_consolidation    0.1392       853.43   

      log.annual.inc    dti  fico  days.with.cr.line  revol.bal  revol.util  \
0          11.350407  19.48   737        5639.958333      28854        52.1   
1          11.082143  14.29   707        2760.000000      33623        76.7   
2          10.373491  11.63   682        4710.000000       3511        25.6   
3          11.350407   8.10   712        2699.958333      33667        73.2   
4          11.299732  14.97   667        4066.000000       4740        39.5   
...              ...    ...   ...                ...        ...         ...   
9573       12.180755  10.39   672       10474.000000     215372        82.1   
9574       11.141862   0.21   722        4380.000000        184         1.1   
9575       10.596635  13.09   687        3450.041667      10036        82.9   
9576       10.819778  19.18   692        1800.000000          0         3.2   
9577       11.264464  16.28   732        4740.000000      37879        57.0   

      inq.last.6mths  delinq.2yrs  pub.rec  not.fully.paid  
0                  0            0        0               0  
1                  0            0        0               0  
2                  1            0        0               0  
3                  1            0        0               0  
4                  0            1        0               0  
...              ...          ...      ...             ...  
9573               2            0        0               1  
9574               5            0        0               1  
9575               8            0        0               1  
9576               5            0        0               1  
9577               6            0        0               1  

[9578 rows x 14 columns]

In [ ]:
import numpy as np
df7 = df.replace(to_replace= np.nan, value= 0)
df7

credit.policy             purpose  int.rate  installment  \
0                 1  debt_consolidation    0.1189       829.10   
1                 1         credit_card    0.1071       228.22   
2                 1  debt_consolidation    0.1357       366.86   
3                 1  debt_consolidation    0.1008       162.34   
4                 1         credit_card    0.1426       102.92   
...             ...                 ...       ...          ...   
9573              0           all_other    0.1461       344.76   
9574              0           all_other    0.1253       257.70   
9575              0  debt_consolidation    0.1071        97.81   
9576              0    home_improvement    0.1600       351.58   
9577              0  debt_consolidation    0.1392       853.43   

      log.annual.inc    dti  fico  days.with.cr.line  revol.bal  revol.util  \
0          11.350407  19.48   737        5639.958333      28854        52.1   
1          11.082143  14.29   707        2760.000000      33623        76.7   
2          10.373491  11.63   682        4710.000000       3511        25.6   
3          11.350407   8.10   712        2699.958333      33667        73.2   
4          11.299732  14.97   667        4066.000000       4740        39.5   
...              ...    ...   ...                ...        ...         ...   
9573       12.180755  10.39   672       10474.000000     215372        82.1   
9574       11.141862   0.21   722        4380.000000        184         1.1   
9575       10.596635  13.09   687        3450.041667      10036        82.9   
9576       10.819778  19.18   692        1800.000000          0         3.2   
9577       11.264464  16.28   732        4740.000000      37879        57.0   

      inq.last.6mths  delinq.2yrs  pub.rec  not.fully.paid  
0                  0            0        0               0  
1                  0            0        0               0  
2                  1            0        0               0  
3                  1            0        0               0  
4                  0            1        0               0  
...              ...          ...      ...             ...  
9573               2            0        0               1  
9574               5            0        0               1  
9575               8            0        0               1  
9576               5            0        0               1  
9577               6            0        0               1  

[9578 rows x 14 columns]

In [ ]:
#conditional statement
a = 10
b = 5

if a > b:
  print("a is greater than the b")
elif a < b:
  print("a is less than the b")
else:
  print("a is equal to b")

a is greater than the b


In [ ]:
fruits = ["apple", "banana", "cherry", "mango"]
for fruit in fruits:
    print(fruit)

count = 0
while count < 5:
    print(count)
    count += 1

apple
banana
cherry
mango
0
1
2
3
4


In [ ]:
fruits = ["apple", "cherry", "strwberry"]
print(len(fruits))
print(id(fruits))
print(type(fruits))
for i in range(5):
  print(i)

3
135937067813440
<class 'list'>
0
1
2
3
4


In [ ]:
class ParentClass:

    def prent_nethod(self):
        print("This parent method")

class ChildClass(ParentClass):

    def child_method(self):
        print("This is child method")

In [ ]:
class Animal:
  def make_sound(self):
    print("Generic animal sound")

class Dog(Animal):
  def make_sound(self):
    print("Woof!")

class Cat(Animal):
  def make_sound(self):
    print("Meow!")

class Poodle(Dog):  # Poodle inherits from Dog
  pass

animals = [Animal(), Dog(), Cat(), Poodle()]
for animal in animals:
  animal.make_sound()

Generic animal sound
Woof!
Meow!
Woof!


In [ ]:

class Parent:
    def func1(self):
        print("This function is in parent class.")




class Child(Parent):
    def func2(self):
        print("This function is in child class.")



object = Child()
object.func1()
object.func2()

This function is in parent class.
This function is in child class.


In [ ]:
class Mother:
    mothername = ""

    def mother(self):
        print(self.mothername)




class Father:
    fathername = ""

    def father(self):
        print(self.fathername)



class Son(Mother, Father):
    def parents(self):
        print("Father :", self.fathername)
        print("Mother :", self.mothername)


s1 = Son()
s1.fathername = "RAM"
s1.mothername = "SITA"
s1.parents()

Father : RAM
Mother : SITA


In [ ]:
# Base class
class Parent:
	def func1(self):
		print("This function is in parent class.")

# Derived class1
class Child1(Parent):
	def func2(self):
		print("This function is in child 1.")

# Derivied class2
class Child2(Parent):
	def func3(self):
		print("This function is in child 2.")


# Driver's code
object1 = Child1()
object2 = Child2()
object1.func1()
object1.func2()
object2.func1()
object2.func3()

This function is in parent class.
This function is in child 1.
This function is in parent class.
This function is in child 2.


In [ ]:
pip install numpy


In [ ]:
import numpy as np
print(np.__version__)

1.25.2


In [ ]:

a = np.array([1, 2, 3, 4, 5])
print(a.shape)

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)


c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c.shape)

(5,)
(2, 3)
(2, 2, 2)


In [ ]:
# Integer array
a = np.array([1, 2, 3, 4, 5])
print(a.dtype)

# Float array
b = np.array([1.0, 2.0, 3.0])
print(b.dtype)

# Complex array
c = np.array([1+2j, 3+4j])
print(c.dtype)

# Boolean array
d = np.array([True, False, True])
print(d.dtype)

int64
float64
complex128
bool


In [ ]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [ ]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a = np.empty(5)
print(a)


[4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323]


In [ ]:
a = np.linspace(0, 1, 5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
print(c)

[5 7 9]


In [ ]:
a = np.array([1, 4, 9])

b = np.sqrt(a)
print(b)

[1. 2. 3.]


In [ ]:
a = np.array([1, 2, 3])
b = 2
c = a + b
print(c)

[3 4 5]


In [ ]:
a = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 2, 4])
print(a[indices])

[1 3 5]


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a[2:6])
print(a[:4])
print(a[5:])
print(a[::2])
print(a[::-1])

[3 4 5 6]
[1 2 3 4]
[6 7 8 9]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1]


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a[::3])
print(a[::-2])

[1 4 7]
[9 7 5 3 1]


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)

# Reshape to a 2D array
b = a.reshape(2, 3)
print(b)

# Reshape to a 3D array
c = a.reshape(2, 1, 3)
print(c)

(6,)
[[1 2 3]
 [4 5 6]]
[[[1 2 3]]

 [[4 5 6]]]


In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])

# Stack arrays horizontally
c = np.hstack((a, b))
print(c)

# Stack arrays vertically
d = np.vstack((a, b))
print(d)

# Stack arrays along a new axis
e = np.stack((a, b), axis=1)
print(e)

[1 2 3 4]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [ ]:
a = np.array([1, 2, 3])
b = np.append(a, [4, 5])
print(b)

c = np.array([[1, 2], [3, 4]])
d = np.append(c, [[5, 6]], axis=0)
print(d)

[1 2 3 4 5]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.insert(a, 2, [10, 20])
print(b)

c = np.array([[1, 2], [3, 4]])
d = np.insert(c, 1, [10, 20], axis=1)
print(d)

[ 1  2 10 20  3  4  5]
[[ 1 10  2]
 [ 3 20  4]]


In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.delete(a, [0, 2])
print(b)

c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.delete(c, 1, axis=1)
print(d)

[2 4 5]
[[1 3]
 [4 6]]


In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.resize(a, (3, 3))
print(b)

[[1 2 3]
 [4 5 1]
 [2 3 4]]


In [ ]:
#Array Operations and Broadcasting:
#Given a 3D array a with shape (2, 3, 4) and a 2D array b with shape (3, 4), perform element-wise multiplication between a and b using broadcasting.


import numpy as np


a = np.random.rand(2, 3, 4)

b = np.random.rand(3, 4)

result = a * b
print(result)



In [ ]:
#Implement a function that takes two 2D arrays c and d with different shapes and performs element-wise operations (addition, subtraction, multiplication, and division) between them using broadcasting. Handle the case where broadcasting is not possible.

import numpy as np

def elementwise_operations(c, d):
    try:
        add = c + d
        print("Addition:\n", addition)


        sub = c - d
        print("Subtraction:\n", subtraction)


        mul = c * d
        print("Multiplication:\n", multiplication)


        div = c / d
        print("Division:\n", division)

    except ValueError as e:
        print("Error:", e)


c = np.random.rand(3, 4)
d = np.random.rand(1, 4)

elementwise_operations(c, d)


In [ ]:
#Create a 2D array e with shape (5, 3) and a 1D array f with length 5. Compute the outer product of e and f using broadcasting.#

import numpy as np

e = np.random.rand(5, 3)
f = np.random.rand(5)


outer_product = e * f[:, np.newaxis]

#
print("2D array", e)
print("1D array", f)
print("Outer product", outer_product)


In [ ]:
#Given a 3D array g with shape (4, 3, 2), extract every other element along the first and second dimensions, but keep all elements along the third dimension.

import numpy as np


g = np.random.rand(4, 3, 2)

result = g[::2, ::2, :]
print("Original array g:\n", g)
print("Extracted array:\n", result)


In [ ]:
#Create a function that takes a 2D array h and an array of row indices i and column indices j. The function should return a new array k where k[m, n] is the sum of the elements in h along the diagonal specified by i[m] and j[n].


import numpy as np

def diagonal_sum(h, i, j):

    k = np.zeros((len(i), len(j)))


    for m in range(len(i)):
        for n in range(len(j)):

            diag_indices = np.diag_indices(min(h.shape))
            k[m, n] = np.sum(h[i[m]:i[m]+1, j[n]:j[n]+1][diag_indices])

    return k


h = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

i = np.array([0, 1, 2])
j = np.array([0, 1, 2])

result = diagonal_sum(h, i, j)
print("Result:\n", result)



In [ ]:
#Implement a function that takes a 2D array l and returns a new array m where each element in m is the product of the corresponding row and column means in l.

import numpy as np

def row_column_means_product(l):

    row_means = np.mean(l, axis=1, keepdims=True)


    column_means = np.mean(l, axis=0, keepdims=True)


    m = row_means * column_means

    return m


l = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

result = row_column_means_product(l)
print("Result:\n", result)


In [ ]:
#Given a 2D array n with shape (4, 6), reshape it into a 3D array with shape (2, 2, 6) and then flatten it back to a 2D array with shape (4, 6).

import numpy as np


n = np.random.rand(4, 6)


reshaped_n = np.reshape(n, (2, 2, 6))


flattened_n = np.flatten(reshaped_n)

print("Original array shape:", n.shape)
print("Reshaped array shape:", reshaped_n.shape)
print("Flattened array shape:", flattened_n.shape)



In [ ]:
#Implement a function that takes a 2D array o and rolls it along the first axis by a specified number of positions. For example, if the input array is [[1, 2, 3], [4, 5, 6]] and the number of positions is 1, the output should be [[4, 5, 6], [1, 2, 3]].

import numpy as np

def roll_array_first_axis(o, positions):

    rolled_array = np.roll(o, positions, axis=0)
    return rolled_array


o = np.array([[1, 2, 3],
              [4, 5, 6]])

positions = 1
result = roll_array_first_axis(o, positions)
print("Original array:\n", o)
print("Rolled array:\n", result)


In [ ]:
#Create a function that takes a 2D array p and replaces all occurrences of a specified value x with the mean of the neighboring elements (horizontally and vertically) in the array.

import numpy as np

def replace_with_neighbor_mean(p, x):

    indices = np.where(p == x)


    for i, j in zip(indices[0], indices[1]):

        neighbor_mean = np.mean([
            p[i-1, j] if i > 0 else 0,
            p[i+1, j] if i < p.shape[0]-1 else 0,
            p[i, j-1] if j > 0 else 0,
            p[i, j+1] if j < p.shape[1]-1 else 0
        ])


        p[i, j] = neighbor_mean

    return p


p = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

x = 5
result = replace_with_neighbor_mean(p, x)
print("Result:\n", result)



OOPS concept

In [ ]:
class MyClass:
    pass

obj = MyClass()

In [ ]:
class MyClass:

    def increment(self):
        if not hasattr(self, 'instance_var'):
            self.instance_var = 0
        self.instance_var += 1
        return self.instance_var

obj = MyClass()

print(obj.increment())
print(obj.increment())

1
2


In [ ]:
class MyClass:
    class_var = 0

    def increment(self):
        MyClass.class_var += 1

obj1 = MyClass()
obj2 = MyClass()
print(MyClass.class_var)
obj1.increment()
print(MyClass.class_var)
obj2.increment()
print(MyClass.class_var)

0
1
2


In [ ]:
class MyClass:
    def my_method(self):
        print("This is a normal method.")

obj = MyClass()
obj.my_method()

This is a normal method.


In [ ]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age


person1 = Person("Alice", 25)
print(person1.name)
print(person1.age)

Alice
25


In [ ]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def __str__(self):
        return f"{self.name} ({self.age})"


person1 = Person("Alice", 25)
print(person1)
print(str(person1))

Alice (25)
Alice (25)


In [ ]:
class Person:
    def __new__(cls, *args, **kwargs):
        print("Creating a new instance of Person")
        return super(Person, cls).__new__(cls)

    def __init__(self, name, age):
        self.name = name
        self.age = age

    def __str__(self):
        return f"{self.name} ({self.age})"


person1 = Person("Alice", 25)
print(person1)


Creating a new instance of Person
Alice (25)


In [ ]:
class MyClass:
    def __init__(self):
        print("Constructor called")

    def __del__(self):
        print("Deconstructor called")

obj = MyClass()

Constructor called


In [ ]:
class MyClass:
    def __init__(self):
        self.data = 0

obj = MyClass()
print(obj.data)

0
Deconstructor called


In [ ]:
class MyClass:
    def __init__(self, value):
        self.data = value

obj = MyClass(10)
print(obj.data)

10


In [ ]:
class MyClass:
    def __init__(self, value=0):
        self.data = value

obj1 = MyClass()
print(obj1.data)
obj2 = MyClass(20)
print(obj2.data)

0
20


In [ ]:
class MyClass:
    def __init__(self, value):
        self.data = value

    def update(self, other):
        self.data += other.data
obj1 = MyClass(10)
obj2 = MyClass(20)

obj1.update(obj2)
print(obj1.data)

In [ ]:
class MyClass:
    def my_method(self, arg1, arg2=0):
        print(f"arg1: {arg1}, arg2: {arg2}")

obj = MyClass()
obj.my_method(10)
obj.my_method(10, 20)

arg1: 10, arg2: 0
arg1: 10, arg2: 20


In [ ]:
class MyClass:
    def __init__(self):
        self.__private_var = 0

    def get_private_var(self):
        return self.__private_var

    def set_private_var(self, value):
        self.__private_var = value

obj = MyClass()

print(obj.get_private_var())

obj.set_private_var(10)
print(obj.get_private_var())

0
10


In [ ]:
class Employee:
    def __init__(self, name, age, salary):

        self.name = name
        self.age = age


        self.__salary = salary

    def get_salary(self):

        return self.__salary

    def set_salary(self, new_salary):

        if new_salary > 0:
            self.__salary = new_salary
        else:
            print("Invalid salary")


employee = Employee("John", 30, 5000)


print(employee.get_salary())


employee.set_salary(6000)


print(employee.get_salary())

5000
6000


In [ ]:
class MyClass:
    def __init__(self):

        self.__hidden_var = 0

    def get_hidden_var(self):

        return self.__hidden_var
    def set_hidden_var(self, value):

        self.__hidden_var = value


obj = MyClass()

obj.set_hidden_var(10)

print(obj.get_hidden_var())

10


In [ ]:
class Person(object):


    def __init__(self, name, idnumber):
        self.name = name
        self.idnumber = idnumber

    def display(self):
        print(self.name)
        print(self.idnumber)

    def details(self):
        print("My name is {}".format(self.name))
        print("IdNumber: {}".format(self.idnumber))


class Employee(Person):
    def __init__(self, name, idnumber, salary, post):
        self.salary = salary
        self.post = post


        Person.__init__(self, name, idnumber)

    def details(self):
        print("My name is {}".format(self.name))
        print("IdNumber: {}".format(self.idnumber))
        print("Post: {}".format(self.post))



a = Employee('Sharanya', 886012, 200000, "Intern")


a.display()
a.details()

Sharanya
886012
My name is Sharanya
IdNumber: 886012
Post: Intern


In [ ]:
class Bird:

    def intro(self):
        print("There are many types of birds.")

    def flight(self):
        print("Most of the birds can fly but some cannot.")

class sparrow(Bird):

    def flight(self):
        print("Sparrows can fly.")

class ostrich(Bird):

    def flight(self):
        print("Ostriches cannot fly.")

obj_bird = Bird()
obj_spr = sparrow()
obj_ost = ostrich()

obj_bird.intro()
obj_bird.flight()

obj_spr.intro()
obj_spr.flight()

obj_ost.intro()
obj_ost.flight()

There are many types of birds.
Most of the birds can fly but some cannot.
There are many types of birds.
Sparrows can fly.
There are many types of birds.
Ostriches cannot fly.


In [ ]:
class car:
    def __init__(self,modelname, year):
        self.modelname = modelname
        self.year = year
    def display(self):
        print(self.modelname,self.year)

c1 = car("Mahendra", 2016)
c1.display()

Mahendra 2016


In [ ]:
 class Human:

    species = "Homo Sapiens"
    def __init__(self, name, age, gender):
        self.name = name
        self.age = age
        self.gender = gender

x = Human("Ron", 15, "Male")
y = Human("Miley", 22, "Female")
print(x.name)
print(y.name)


Ron
Miley


In [ ]:
class Human:

    species = "Homo Sapiens"
    def __init__(self, name, age, gender):
        self.name = name
        self.age = age
        self.gender = gender

Human.species = "Sapiens"
obj = Human("Brek",11,"male")
print(obj.species)

Sapiens


In [ ]:
class Human:

    species = "Homo Sapiens"
    def __init__(self, name, age, gender):
        self.name = name
        self.age = age
        self.gender = gender


    def speak(self):
        return f"Hello everyone! I am {self.name}"


    def eat(self, favouriteDish):
        return f"I love to eat {favouriteDish}!!!"

x = Human("Ciri",18,"female")
print(x.speak())
print(x.eat("momos"))


Hello everyone! I am Ciri
I love to eat momos!!!


In [ ]:
class Human:     #parent class
    def __init__(self, name, age, gender):
        self.name = name
        self.age = age
        self.gender = gender

    def description(self):
        print(f"Hey! My name is {self.name}, I'm a {self.gender} and I'm {self.age} years old")

class Boy(Human):    #child class
    def schoolName(self, schoolname):
        print(f"I study in {schoolname}")


b = Boy('John', 15, 'male')
b.description()
b.schoolName("Sunshine Model School")


Hey! My name is John, I'm a male and I'm 15 years old
I study in Sunshine Model School


In [ ]:
class Human:
    def __init__(self,name,age,gender):
        self.name = name
        self.age = age
        self.gender = gender
    def description(self):
        print(f"Hey! My name is {self.name}, I'm a {self.gender} and I'm {self.age} years old")

    def dance(self):
        print("I can dance")

class Girl(Human):
    def dance(self):
        print("I can do classic dance")
    def activity(self):
        super().dance()
g = Girl('Lily', 20, 'girl')
g.description()
g.activity()


Hey! My name is Lily, I'm a girl and I'm 20 years old
I can dance


In [ ]:
print(len('deepa'))
print(len([1,2,5,9]))
print(len({'1':'apple','2':'cherry','3':'banana'}))


5
4
3


In [ ]:
class Monkey:
    def color(self):
        print("The monkey is yellow coloured!")

    def eats(self):
        print("The monkey eats bananas!")


class Rabbit:
    def color(self):
        print("The rabbit is white coloured!")

    def eats(self):
        print("The rabbit eats carrots!")


mon = Monkey()
rab = Rabbit()
for animal in (mon, rab):
    animal.color()
    animal.eats()


The monkey is yellow coloured!
The monkey eats bananas!
The rabbit is white coloured!
The rabbit eats carrots!


### **Inheritance Practice**

In [ ]:
class ParentClass:
    def prent_nethod(self):
        print("This parent method")

class ChildClass(ParentClass):
    def child_method(self):
        print("This is child method")

In [ ]:
class Animal:
  def make_sound(self):
    print("Generic animal sound")

class Dog(Animal):
  def make_sound(self):
    print("Woof!")

class Cat(Animal):
  def make_sound(self):
    print("Meow!")

class Poodle(Dog):  # Poodle inherits from Dog
  pass

animals = [Animal(), Dog(), Cat(), Poodle()]
for animal in animals:
  animal.make_sound()

Generic animal sound
Woof!
Meow!
Woof!


In [ ]:
# Base class
class Parent:
    def func1(self):
        print("This function is in parent class.")

# Derived class


class Child(Parent):
    def func2(self):
        print("This function is in child class.")


# Driver's code
object = Child()
object.func1()
object.func2()

This function is in parent class.
This function is in child class.


In [ ]:
class Mother:
    mothername = ""

    def mother(self):
        print(self.mothername)

# Base class2


class Father:
    fathername = ""

    def father(self):
        print(self.fathername)

# Derived class


class Son(Mother, Father):
    def parents(self):
        print("Father :", self.fathername)
        print("Mother :", self.mothername)


# Driver's code
s1 = Son()
s1.fathername = "RAM"
s1.mothername = "SITA"
s1.parents()

Father : RAM
Mother : SITA


In [ ]:
class Grandfather:

	def __init__(self, grandfathername):
		self.grandfathername = grandfathername

# Intermediate class
class Father(Grandfather):
	def __init__(self, fathername, grandfathername):
		self.fathername = fathername

		# invoking constructor of Grandfather class
		Grandfather.__init__(self, grandfathername)

# Derived class
class Son(Father):
	def __init__(self, sonname, fathername, grandfathername):
		self.sonname = sonname

		# invoking constructor of Father class
		Father.__init__(self, fathername, grandfathername)

	def print_name(self):
		print('Grandfather name :', self.grandfathername)
		print("Father name :", self.fathername)
		print("Son name :", self.sonname)


# Driver code
s1 = Son('Prince', 'Rampal', 'Lal mani')
print(s1.grandfathername)
s1.print_name()

Lal mani
Grandfather name : Lal mani
Father name : Rampal
Son name : Prince


In [ ]:
# Base class
class Parent:
	def func1(self):
		print("This function is in parent class.")

# Derived class1
class Child1(Parent):
	def func2(self):
		print("This function is in child 1.")

# Derivied class2
class Child2(Parent):
	def func3(self):
		print("This function is in child 2.")


# Driver's code
object1 = Child1()
object2 = Child2()
object1.func1()
object1.func2()
object2.func1()
object2.func3()

This function is in parent class.
This function is in child 1.
This function is in parent class.
This function is in child 2.


In [ ]:
class School:
	def func1(self):
		print("This function is in school.")


class Student1(School):
	def func2(self):
		print("This function is in student 1. ")


class Student2(School):
	def func3(self):
		print("This function is in student 2.")


class Student3(Student1, School):
	def func4(self):
		print("This function is in student 3.")

In [ ]:

class Shape:

  def area(self):
    raise NotImplementedError("Subclasses must implement area()")


class Square(Shape):

  def __init__(self, side):
    self.side = side

  def area(self):
    #Calculates area of square
    return self.side * self.side

class Circle(Shape):

  def __init__(self, radius):
    self.radius = radius

  def area(self):
    #Calculates area of circle
    return 3.14 * self.radius * self.radius

# Create objects of Square and Circle
square = Square(5)
circle = Circle(3)


# Call the overridden area method from each subclass
print(f"Area of square: {square.area()}")
print(f"Area of circle: {circle.area()}")

Area of square: 25
Area of circle: 28.259999999999998


In [ ]:
class Shape:

  def info(self):
    print(f"I am a {type(self).__name__}.")

class ColoredShape(Shape):

  def __init__(self):
    pass

  def info(self):
    super().info() # Call info from Shape
    print(f"I am also colored.")

class RedSquare(ColoredShape):

  # No __init__ defined here

  def info(self):
    super().info()  # Call info from ColoredShape
    print(f"I am a red square.")

# Create objects (these won't have color set since ColoredShape lacks __init__)
red_square = RedSquare()

red_square.info()

I am a RedSquare.
I am also colored.
I am a red square.


In [ ]:
class Emp():
    def __init__(self, id, name, Add):
        self.id = id
        self.name = name
        self.Add = Add

# Class freelancer inherits EMP
class Freelance(Emp):
    def __init__(self, id, name, Add, Emails):
        super().__init__(id, name, Add)
        self.Emails = Emails

Emp_1 = Freelance(103, "Suraj kr gupta", "Noida" , "SKG@gmails")
print('The ID is:', Emp_1.id)
print('The Name is:', Emp_1.name)
print('The Address is:', Emp_1.Add)
print('The Emails is:', Emp_1.Emails)

The ID is: 103
The Name is: Suraj kr gupta
The Address is: Noida
The Emails is: SKG@gmails


In [ ]:
class Animal:
    def __init__(self, species):
        self.species = species

    def __str__(self):
        return f"I am a {self.species}"

# Child class inherits Parent class(Animal)
class Dog(Animal):
    def __init__(self, breed):
        super().__init__("dog")
        self.breed = breed

    def __str__(self):
        return super().__str__() + f" of breed {self.breed}"

# Creating an instance of Dog
my_dog = Dog("Labrador")

# Printing the Dog instance
print(my_dog)

I am a dog of breed Labrador


In [ ]:
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)
x = Person("John", "Doe")
x.printname()

John Doe


In [ ]:
class Student(Person):
  def __init__(self, fname, lname, year):
    super().__init__(fname, lname)
    self.graduationyear = year

x = Student("Mike", "Olsen", 2019)

In [ ]:
class Student(Person):
  def __init__(self, fname, lname, year):
    super().__init__(fname, lname)
    self.graduationyear = year

  def welcome(self):
    print("Welcome", self.firstname, self.lastname, "to the class of", self.graduationyear)

In [ ]:
class SuperClass:

    def super_method(self):
        print("Super Class method called")


class DerivedClass1(SuperClass):
    def derived1_method(self):
        print("Derived class 1 method called")
class DerivedClass2(DerivedClass1):

    def derived2_method(self):
        print("Derived class 2 method called")


d2 = DerivedClass2()

d2.super_method()

d2.derived1_method()
d2.derived2_method()

Super Class method called
Derived class 1 method called
Derived class 2 method called


In [ ]:
class SuperClass1:
    def info(self):
        print("Super Class 1 method called")

class SuperClass2:
    def info(self):
        print("Super Class 2 method called")

class Derived(SuperClass1, SuperClass2):
    pass

d1 = Derived()
d1.info()



Super Class 1 method called


In [ ]:
class School:
    def func1(self):
        print("This function is in school.")


class Student1(School):
    def func2(self):
        print("This function is in student 1. ")


class Student2(School):
    def func3(self):
        print("This function is in student 2.")


class Student3(Student1, School):
    def func4(self):
        print("This function is in student 3.")


object = Student3()
object.func1()
object.func2()

This function is in school.
This function is in student 1. 


### Exception Handling Practice


In [ ]:
try:
    x = 10
    y = 0
    result = x / y
    print(result)
except ZeroDivisionError:
    print("Error: Cannot divide by zero!")

Error: Cannot divide by zero!


In [ ]:

try:
    x = 10
    y = 0
    result = x / y
    print(result)

except ZeroDivisionError:
    print("Error: Cannot divide by zero!")

except ValueError:
    print("Error: Invalid value!")

Error: Cannot divide by zero!


In [ ]:
 try:

    if x == 5:
        print("x is equal to 5")
except SyntaxError:
    print("SyntaxError occurred")

In [ ]:
try:
    # Code that passes an invalid value to a function
    int("hello")  # The string "hello" cannot be converted to an integer
except ValueError:
    print("ValueError occurred")


ValueError occurred


In [ ]:
class InvalidAgeError(Exception):
    """Raised when the input age is invalid"""
    pass

def validate_age(age):
    if age < 0:
        raise InvalidAgeError("Age cannot be negative")
    elif age > 120:
        raise InvalidAgeError("Age cannot be greater than 120")
    else:
        print("Valid age")

try:
    validate_age(-5)
except InvalidAgeError:
    print("Invalid age provided")

Invalid age provided


In [ ]:
try:
    x = 10 / 0  # This will raise a ZeroDivisionError
except ZeroDivisionError:
    print("Can't divide by zero!")

Can't divide by zero!


In [ ]:
try:
    x = int(input("Enter a number: "))
    y = 10 / x
except ValueError:
    print("Invalid input! Please enter a number.")
except ZeroDivisionError:
    print("Can't divide by zero!")
else:
    print(f"Result: {y}")

Enter a number: 3
Result: 3.3333333333333335


In [ ]:
try:

    result = 10 / 0
except ZeroDivisionError as e:
    print("Error:", e)
    print("Type:", type(e))
    print("Details:", e.args)

Error: division by zero
Type: <class 'ZeroDivisionError'>
Details: ('division by zero',)


In [ ]:

def divide_numbers(x, y):
    if y == 0:
        raise ValueError("Cannot divide by zero")
    return x / y

try:
    result = divide_numbers(10, 0)
except ValueError as e:
    print("Error:", e)


Error: Cannot divide by zero


In [ ]:
class CustomError(Exception):
    pass

def check_value(x):
    if x < 0:
        raise CustomError("Value cannot be negative")

try:
    check_value(-5)
except CustomError as e:
    print("Custom error occurred:", e)

Custom error occurred: Value cannot be negative


In [ ]:
def divide(x, y):
    try:
        result = x / y
        print("Result:", result)
    except ZeroDivisionError:
        print("Cannot divide by zero")


divide(10, 0)

Cannot divide by zero


In [ ]:
def process_data(data):
    try:
        result = 10 / data
    except ZeroDivisionError:
        raise ValueError("Invalid data") from None

try:
    process_data(0)
except ValueError as e:
    print("Error:", e)


Error: Invalid data


In [ ]:
def main():
    try:
        result = 10 / 0
    except ZeroDivisionError :
        print("An error occurred: Cannot divide by zero")

if __name__ == "__main__":
    main()

An error occurred: Cannot divide by zero


In [ ]:
def divide(x, y):
    if y == 0:
        raise ValueError("Cannot divide by zero")
    return x / y

try:
    result = divide(10, 0)
except ValueError as e:
    print("Error:", e)

Error: Cannot divide by zero


In [ ]:
def divide(x, y):
    try:
        result = x / y
    except ZeroDivisionError:
        print("Cannot divide by zero")
        result = None
    finally:
        print("Division operation complete")

    return result

result1 = divide(10, 2)
print("Result 1:", result1)

result2 = divide(10, 0)
print("Result 2:", result2)


Division operation complete
Result 1: 5.0
Cannot divide by zero
Division operation complete
Result 2: None


In [ ]:
def divide_numbers(num1, num2):
    if num2 == 0:
        raise ZeroDivisionError("Cannot divide by zero")
    else:
        result = num1 / num2
        return result


try:
    print(divide_numbers(10, 2))
    print(divide_numbers(5, 0))
except ZeroDivisionError:
    print("Error: Division by zero is not allowed")

5.0
Error: Division by zero is not allowed


In [ ]:
class PalindromeError(Exception):
    pass

def is_palindrome(input_str):
    if not isinstance(input_str, str):
        raise PalindromeError("Input must be a string")


    clean_str = input_str.replace(" ", "").lower()


    if clean_str == clean_str[::-1]:
        return True
    else:
        return False


try:
    print(is_palindrome("racecar"))
    print(is_palindrome("A man a plan a canal Panama"))
    print(is_palindrome(123))
except PalindromeError as e:
    print(e)

True
True
Input must be a string


In [ ]:

numbers = [10, 0, 5, 20, 3]

for num in numbers:
    try:
        result = num / 0
        print(f"{num} / 0 = {result}")
    except ZeroDivisionError:
        print(f"Error: Cannot divide {num} by zero")
    finally:
        print("Iteration completed")
        print("-----------------------")

print("End of script")

Error: Cannot divide 10 by zero
Iteration completed
-----------------------
Error: Cannot divide 0 by zero
Iteration completed
-----------------------
Error: Cannot divide 5 by zero
Iteration completed
-----------------------
Error: Cannot divide 20 by zero
Iteration completed
-----------------------
Error: Cannot divide 3 by zero
Iteration completed
-----------------------
End of script


In [ ]:
def divide_numbers(num1, num2):
    try:
        result = num1 / num2
        print(f"{num1} / {num2} = {result}")
    except ZeroDivisionError:
        print(f"Error: Cannot divide {num1} by zero")
    finally:
        print("Division operation completed")

divide_numbers(10, 2)
divide_numbers(5, 0)

10 / 2 = 5.0
Division operation completed
Error: Cannot divide 5 by zero
Division operation completed


In [ ]:
try:
    num_str = input("Enter a number: ")
    num = int(num_str)
    print("Integer value:", num)
except ValueError:
    print("Error: Could not convert '{}' to an integer.".format(num_str))

Enter a number: 4
Integer value: 4


In [ ]:
import math

class NegativeNumberError(Exception):
    pass

def sqrt(num):
    if num < 0:
        raise NegativeNumberError("Cannot calculate square root of a negative number")
    return math.sqrt(num)

try:
    print(sqrt(25))
    print(sqrt(-4))
except NegativeNumberError as e:
    print(e)

In [ ]:
x = 5
y = "hello"
try:
    z = x + y
except TypeError:
    print("Error: cannot add an int and a str")

Error: cannot add an int and a str


In [ ]:
a = [1, 2, 3]
try:
    print ("Second element = %d" %(a[1]))

    print ("Fourth element = %d" %(a[3]))

except:
    print ("An error occurred")

Second element = 2
An error occurred


In [ ]:
def fun(a):
    if a < 4:

        b = a/(a-3)
    print("Value of b = ", b)

try:
    fun(3)
    fun(5)
except ZeroDivisionError:
    print("ZeroDivisionError Occurred and Handled")
except NameError:
    print("NameError Occurred and Handled")

ZeroDivisionError Occurred and Handled


In [ ]:
def AbyB(a , b):
    try:
        c = ((a+b) / (a-b))
    except ZeroDivisionError:
        print ("a/b result in 0")
    else:
        print (c)
AbyB(2.0, 3.0)
AbyB(3.0, 3.0)

-5.0
a/b result in 0


In [ ]:
try:
    k = 5//0
    print(k)

except ZeroDivisionError:
    print("Can't divide by zero")

finally:
    print('This is always executed')

Can't divide by zero
This is always executed


In [ ]:
try:
    numerator = 10
    denominator = 0

    result = numerator/denominator

    print(result)
except:
    print("Error: Denominator cannot be 0.")



Error: Denominator cannot be 0.


In [ ]:
try:

    even_numbers = [2,4,6,8]
    print(even_numbers[5])

except ZeroDivisionError:
    print("Denominator cannot be 0.")

except IndexError:
    print("Index Out of Bound.")



Index Out of Bound.


In [ ]:

try:
    num = int(input("Enter a number: "))
    assert num % 2 == 0
except:
    print("Not an even number!")
else:
    reciprocal = 1/num
    print(reciprocal)

In [ ]:

class InvalidAgeException(Exception):
    "Raised when the input value is less than 18"
    pass


number = 18

try:
    input_num = int(input("Enter a number: "))
    if input_num < number:
        raise InvalidAgeException
    else:
        print("Eligible to Vote")

except InvalidAgeException:
    print("Exception occurred: Invalid Age")

Enter a number: 7
Exception occurred: Invalid Age


In [ ]:
class SalaryNotInRangeError(Exception):


    def __init__(self, salary, message="Salary is not in (5000, 15000) range"):
        self.salary = salary
        self.message = message
        super().__init__(self.message)


salary = int(input("Enter salary amount: "))
if not 5000 < salary < 15000:
    raise SalaryNotInRangeError(salary)

Enter salary amount: 55500


SalaryNotInRangeError: Salary is not in (5000, 15000) range

In [ ]:

class InvalidAgeException(Exception):
    "Raised when the input value is less than 18"
    pass

number = 18

try:
    input_num = int(input("Enter a number: "))
    if input_num < number:
        raise InvalidAgeException
    else:
        print("Eligible to Vote")

except InvalidAgeException:
    print("Exception occurred: Invalid Age")

Enter a number: 18
Eligible to Vote


### LIST

In [1]:
fruits = ["apple", "banana", "cherry"]

fruits.append("orange")
print(f"Append: {fruits}")


fruits.insert(1, "grape")
print(f"Insert: {fruits}")


fruits.remove("banana")
print(f"Remove: {fruits}")


fruits_shallow_copy = fruits.copy()
fruits_shallow_copy[0] = "lemon"
print(f"Shallow Copy: {fruits_shallow_copy}, Original: {fruits}")


import copy
fruits_deep_copy = copy.deepcopy(fruits)
fruits_deep_copy[0] = "kiwi"
print(f"Deep Copy: {fruits_deep_copy}, Original: {fruits}")


fruits.append("apple")
apple_count = fruits.count("apple")
print(f"Count of 'apple': {apple_count}")

more_fruits = ["pear", "pineapple"]
fruits.extend(more_fruits)
print(f"Extend: {fruits}")

apple_index = fruits.index("apple")
print(f"Index of 'apple': {apple_index}")


fruits.sort()
print(f"Sort: {fruits}")


fruits.reverse()
print(f"Reverse: {fruits}")


fruits.clear()
print(f"Clear: {fruits}")


removed_fruit = more_fruits.pop()
print(f"Pop: {removed_fruit}, Remaining: {more_fruits}")

Append: ['apple', 'banana', 'cherry', 'orange']
Insert: ['apple', 'grape', 'banana', 'cherry', 'orange']
Remove: ['apple', 'grape', 'cherry', 'orange']
Shallow Copy: ['lemon', 'grape', 'cherry', 'orange'], Original: ['apple', 'grape', 'cherry', 'orange']
Deep Copy: ['kiwi', 'grape', 'cherry', 'orange'], Original: ['apple', 'grape', 'cherry', 'orange']
Count of 'apple': 2
Extend: ['apple', 'grape', 'cherry', 'orange', 'apple', 'pear', 'pineapple']
Index of 'apple': 0
Sort: ['apple', 'apple', 'cherry', 'grape', 'orange', 'pear', 'pineapple']
Reverse: ['pineapple', 'pear', 'orange', 'grape', 'cherry', 'apple', 'apple']
Clear: []
Pop: pineapple, Remaining: ['pear']


In [2]:
squares = [x ** 2 for x in range(10)]
print("List of squares:", squares)


even_numbers = [x for x in range(20) if x % 2 == 0]
print("Even numbers:", even_numbers)


words = ["hello", "world", "python", "code"]
uppercased_words = [word.upper() for word in words]
print("Uppercased words:", uppercased_words)


number_square_pairs = [(x, x ** 2) for x in range(10)]
print("Number-Square pairs:", number_square_pairs)


nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
flattened_list = [item for sublist in nested_list for item in sublist]
print("Flattened list:", flattened_list)

List of squares: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
Even numbers: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
Uppercased words: ['HELLO', 'WORLD', 'PYTHON', 'CODE']
Number-Square pairs: [(0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25), (6, 36), (7, 49), (8, 64), (9, 81)]
Flattened list: [1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
fruits = ["apple", "banana", "cherry", "date", "elderberry"]

# Accessing elements using positive indexing
first_fruit = fruits[0]
second_fruit = fruits[1]
last_fruit = fruits[-1]
print("First fruit:", first_fruit)
print("Second fruit:", second_fruit)
print("Last fruit:", last_fruit)

# Accessing elements using negative indexing
second_last_fruit = fruits[-2]
third_last_fruit = fruits[-3]
print("Second last fruit:", second_last_fruit)
print("Third last fruit:", third_last_fruit)

# Get the value of an element at a specific index
middle_fruit = fruits[2]
print("Middle fruit:", middle_fruit)

# Change the value of an element at a specific index
fruits[1] = "blueberry"
print("Updated fruits:", fruits)

First fruit: apple
Second fruit: banana
Last fruit: elderberry
Second last fruit: date
Third last fruit: cherry
Middle fruit: cherry
Updated fruits: ['apple', 'blueberry', 'cherry', 'date', 'elderberry']


In [4]:
fruits = ["apple", "banana", "cherry", "date", "elderberry", "fig", "grape"]


subset1 = fruits[1:4]
print("Positive Slicing:", subset1)


subset2 = fruits[1:6:2]
print("Positive Slicing with Step:", subset2)

subset3 = fruits[-3:]
print("Negative Slicing:", subset3)


subset4 = fruits[-2:-5:-1]
print("Negative Slicing with Reverse:", subset4)


middle_subset = fruits[2:5]
print("Retrieve a Portion:", middle_subset)

fruits[1:3] = ["blueberry", "cranberry"]
print("Update a Slice:", fruits)


del fruits[2:4]
print("Delete a Slice:", fruits)


fruits[1:1] = ["kiwi", "mango"]
print("Insert into a Slice:", fruits)

Positive Slicing: ['banana', 'cherry', 'date']
Positive Slicing with Step: ['banana', 'date', 'fig']
Negative Slicing: ['elderberry', 'fig', 'grape']
Negative Slicing with Reverse: ['fig', 'elderberry', 'date']
Retrieve a Portion: ['cherry', 'date', 'elderberry']
Update a Slice: ['apple', 'blueberry', 'cranberry', 'date', 'elderberry', 'fig', 'grape']
Delete a Slice: ['apple', 'blueberry', 'elderberry', 'fig', 'grape']
Insert into a Slice: ['apple', 'kiwi', 'mango', 'blueberry', 'elderberry', 'fig', 'grape']


In [6]:
fruits = ["apple", "banana", "cherry", "date", "elderberry"]


has_banana = "banana" in fruits
print("Is 'banana' in the list?", has_banana)

# Finding the index of an element
banana_index = fruits.index("banana")
print("Index of 'banana':", banana_index)

# Iterating through the list to find a specific element
element_to_find = "date"
found_element = None
for fruit in fruits:
    if fruit == element_to_find:
        found_element = fruit
        break
print("Found element:", found_element)

Is 'banana' in the list? True
Index of 'banana': 1
Found element: date


In [5]:
from functools import reduce


numbers = [1, 2, 3, 4, 5]
sum_result = reduce(lambda x, y: x + y, numbers)
print("Sum using reduce:", sum_result)


max_result = reduce(lambda x, y: x if x > y else y, numbers)
print("Max value using reduce:", max_result)

squares = list(map(lambda x: x ** 2, [1, 2, 3, 4, 5]))
print("Squares using map:", squares)


words = ["apple", "banana", "cherry"]
uppercased = list(map(str.upper, words))
print("Uppercased words using map:", uppercased)


even_numbers = list(filter(lambda x: x % 2 == 0, [1, 2, 3, 4, 5, 6]))
print("Even numbers using filter:", even_numbers)


long_words = list(filter(lambda word: len(word) > 5, ["apple", "banana", "cherry", "date", "elderberry"]))
print("Long words using filter:", long_words)


fruits = ["apple", "banana", "cherry"]
quantities = [10, 20, 30]
fruit_quantities = list(zip(fruits, quantities))
print("Zipped lists:", fruit_quantities)

colors = ["red", "yellow", "red"]
fruit_colors_quantities = list(zip(fruits, colors, quantities))
print("Zipped three lists:", fruit_colors_quantities)

Sum using reduce: 15
Max value using reduce: 5
Squares using map: [1, 4, 9, 16, 25]
Uppercased words using map: ['APPLE', 'BANANA', 'CHERRY']
Even numbers using filter: [2, 4, 6]
Long words using filter: ['banana', 'cherry', 'elderberry']
Zipped lists: [('apple', 10), ('banana', 20), ('cherry', 30)]
Zipped three lists: [('apple', 'red', 10), ('banana', 'yellow', 20), ('cherry', 'red', 30)]


In [7]:
languages = ['Python', 'Swift', 'C++']


print(languages[0])

print(languages[2])   # C++

Python
C++


In [8]:
fruits = ['apple', 'banana', 'orange']
print('Original List:', fruits)


fruits.append('cherry')

print('Updated List:', fruits)

Original List: ['apple', 'banana', 'orange']
Updated List: ['apple', 'banana', 'orange', 'cherry']


In [9]:
colors = ['Red', 'Black', 'Green']
print('Original List:', colors)

colors[2] = 'Blue'

print('Updated List:', colors)

Original List: ['Red', 'Black', 'Green']
Updated List: ['Red', 'Black', 'Blue']


In [10]:
numbers = [2,4,7,9]


numbers.remove(4)

print(numbers)

[2, 7, 9]


In [11]:
cars = ['BMW', 'Mercedes', 'Tesla']

print('Total Elements: ', len(cars))


Total Elements:  3


### TUPLE

In [12]:
x= ("apple", "banana", "cherry", "apple", "cherry")
print(x)

thistuple = tuple(("apple", "banana", "cherry"))
print(len(thistuple))

('apple', 'banana', 'cherry', 'apple', 'cherry')
3


In [13]:
tuple1 = ("abc", 34, True, 40, "male")
print(tuple1)


('abc', 34, True, 40, 'male')


In [15]:
q = tuple(("apple", "banana", "cherry"))
print(q)

w = ("apple", "banana", "cherry")
print(w[1])


e = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(e[2:5])

t= ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(t[:4])

le = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(le[-4:-1])

('apple', 'banana', 'cherry')
banana
('cherry', 'orange', 'kiwi')
('apple', 'banana', 'cherry', 'orange')
('orange', 'kiwi', 'melon')


In [16]:
thistuple = ("apple", "banana", "cherry")
y = list(thistuple)
y.append("orange")
thistuple = tuple(y)

print(thistuple)


('apple', 'banana', 'cherry', 'orange')


In [17]:
thistuple = ("apple", "banana", "cherry")
del thistuple
print(thistuple)

NameError: name 'thistuple' is not defined

In [18]:
fruits = ("apple", "mango", "papaya", "pineapple", "cherry")

(green, *tropic, red) = fruits

print(green)
print(tropic)
print(red)

apple
['mango', 'papaya', 'pineapple']
cherry


In [19]:
i = ("apple", "banana", "cherry")
for x in i:
  print(x)

apple
banana
cherry


In [ ]:
repeated_number = 5
repetitions = 3
repeated_tuple = tuple(range(repeated_number)) * repetitions

print("Tuple with repeated elements:", repeated_tuple)

tuple = ("apple", "banana", "cherry")
i = 0
while i < len(tuple):
  print(tuple[i])
  i = i + 1

In [20]:
tuple1 = (1, 2, 3)
tuple2 = (4, 5, 6)

joined_tuple = tuple1 + tuple2

print("Joined tuple:", joined_tuple)

Joined tuple: (1, 2, 3, 4, 5, 6)


In [21]:
fruits = ("apple", "banana", "cherry")
mytuple = fruits * 2

print(mytuple)

('apple', 'banana', 'cherry', 'apple', 'banana', 'cherry')


In [23]:
my_list = ['apple', 'banana', 'cherry', 'date']
print(my_list[:2])
print(my_list[2:])


numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]
numbers[1:4] = [10, 20, 30]
print(numbers)

numbers[4:4] = [40, 50]
print(numbers)

['apple', 'banana']
['cherry', 'date']
[1, 10, 20, 30, 5, 6, 7, 8, 9]
[1, 10, 20, 30, 40, 50, 5, 6, 7, 8, 9]


In [22]:
Tuple1 = (0, 1, 2, 3, 2, 3, 1, 3, 2)
Tuple2 = ('python', 'geek', 'python','for', 'java', 'python')

res = Tuple1.count(3)
print('Count of 3 in Tuple1 is:', res)

res = Tuple2.count('python')
print('Count of Python in Tuple2 is:', res)



Tuple = (0, 1, (2, 3), (2, 3), 1, [3, 2], 'geeks', (0,))

res = Tuple.count((2, 3))
print('Count of (2, 3) in Tuple is:', res)


res = Tuple.count([3, 2])
print('Count of [3, 2] in Tuple is:', res)


3.
fruits_tuple = ("apple", "banana", "orange", "apple", "grape")
apple_count = fruits_tuple.count("apple")
print("Number of apples:", apple_count)


4.
numbers_tuple = (1, 2, 3, 2, 1, 4)
count_1 = numbers_tuple.count(1)
count_2 = numbers_tuple.count(2)
print("Count of 1:", count_1)
print("Count of 2:", count_2)

Count of 3 in Tuple1 is: 3
Count of Python in Tuple2 is: 3
Count of (2, 3) in Tuple is: 2
Count of [3, 2] in Tuple is: 1
Number of apples: 2
Count of 1: 2
Count of 2: 2


In [24]:
fruits_tuple = ("apple", "banana", "cherry", "banana")


index_of_banana = fruits_tuple.index("banana")
print(index_of_banana)

try:
  index_of_mango = fruits_tuple.index("mango")
except ValueError:
  print("Element 'mango' not found in the tuple")

1
Element 'mango' not found in the tuple


In [28]:
numbers_list = [1, 5, 2, 8, 3]
largest = max(numbers_list)
print("Largest number:", largest)  # Output: Largest number: 8

numbers_tuple = (10, 20, 30)
largest = max(numbers_tuple)
print("Largest number in tuple:", largest)

Largest number: 8
Largest number in tuple: 30


In [29]:
numbers_list = [1, 5, 2, 8, 3]
smallest = min(numbers_list)
print("Smallest number:", smallest)  # Output: Smallest number: 1

numbers_tuple = (10, 20, 30)
smallest = min(numbers_tuple)
print("Smallest number in tuple:", smallest)

Smallest number: 1
Smallest number in tuple: 10


In [30]:
numbers_list = [1, 5, 2, 8, 3]
sorted_list = sorted(numbers_list)
print("Sorted list:", sorted_list)  # Output: Sorted list: [1, 2, 3, 5, 8]

numbers_tuple = (10, 20, 30, 4, 5)
sorted_tuple = sorted(numbers_tuple)
print("Sorted tuple:", sorted_tuple)

Sorted list: [1, 2, 3, 5, 8]
Sorted tuple: [4, 5, 10, 20, 30]


In [31]:
fruits_list = ["apple", "banana", "cherry"]
fruits_tuple = ("mango", "kiwi", "grape")

smallest_fruit_list = min(fruits_list)
smallest_fruit_tuple = min(fruits_tuple)

print("Smallest fruit in list:", smallest_fruit_list)
print("Smallest fruit in tuple:", smallest_fruit_tuple)

Smallest fruit in list: apple
Smallest fruit in tuple: grape


In [32]:
numbers_list = [1, 5, 2, 8]
numbers_tuple = (3, 7, 9, 0)

largest_number_list = max(numbers_list)
largest_number_tuple = max(numbers_tuple)

print("Largest number in list:", largest_number_list)
print("Largest number in tuple:", largest_number_tuple)

Largest number in list: 8
Largest number in tuple: 9


In [ ]:
numbers_list = [4, 7, 2, 11]
numbers_tuple = (6, 3, 8, 1)

list_sum = sum(numbers_list)
tuple_sum = sum(numbers_tuple)

print("Sum of list elements:", list_sum)
print("Sum of tuple elements:", tuple_sum)

### DICTIONARY

In [33]:
empty_dict = dict()

person = {'name': 'John', 'age': 30, 'city': 'New York'}

In [34]:
print(person['name'])
print(person.get('age'))

person['age'] = 31

John
30


In [35]:
person = {
    'name': 'John Doe',
    'age': 30,
    'address': {
        'street': '123 Main St',
        'city': 'New York',
        'state': 'NY'
    }
}


print(person['name'])
print(person['address']['city'])

John Doe
New York


In [38]:
config = {
    'debug': True,
    'log_file': 'app.log',
    'database': {
        'host': 'localhost',
        'user': 'root',
        'password': 'secret'
    }
}


debug_mode = config['debug']
log_file = config['log_file']
db_host = config['database']['host']

In [37]:
sentence = "Hello, world! Hello, Python!"
word_counts = {}

for word in sentence.split():
    if word in word_counts:
        word_counts[word] += 1
    else:
        word_counts[word] = 1

print(word_counts)

{'Hello,': 2, 'world!': 1, 'Python!': 1}


In [39]:
data = [
    {'name': 'John', 'age': 25, 'city': 'New York'},
    {'name': 'Jane', 'age': 30, 'city': 'Los Angeles'},
    {'name': 'Bob', 'age': 35, 'city': 'Chicago'}
]


filtered_data = [person for person in data if person['age'] > 30]
print(filtered_data)


grouped_data = {}
for person in data:
    city = person['city']
    if city in grouped_data:
        grouped_data[city].append(person)
    else:
        grouped_data[city] = [person]

print(grouped_data)

[{'name': 'Bob', 'age': 35, 'city': 'Chicago'}]
{'New York': [{'name': 'John', 'age': 25, 'city': 'New York'}], 'Los Angeles': [{'name': 'Jane', 'age': 30, 'city': 'Los Angeles'}], 'Chicago': [{'name': 'Bob', 'age': 35, 'city': 'Chicago'}]}


In [40]:
keys = person.keys()
print(keys)

dict_keys(['name', 'age', 'city'])


In [41]:
values = person.values()
print(values)

dict_values(['Bob', 35, 'Chicago'])


In [42]:
items = person.items()
print(items)

dict_items([('name', 'Bob'), ('age', 35), ('city', 'Chicago')])


In [43]:
print(person.get('Name'))
print(person.get('phonenumber', 0))

None
0


In [44]:
my_dict = {'apple': 1, 'banana': 2, 'orange': 3}
removed_value = my_dict.pop('banana')
print(removed_value)
print(my_dict)

2
{'apple': 1, 'orange': 3}


In [45]:
my_dict.clear()
print(my_dict)

{}


In [46]:
new_dic = person.copy()
print(new_dic)

{'name': 'Bob', 'age': 35, 'city': 'Chicago'}


In [47]:
person['email'] = 'john@example.com'
popped_value = person.pop('age')

In [48]:
numbers = [1, 2, 3, 4, 5]


squares = {num: num**2 for num in numbers}
print(squares)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [49]:
original = {'a': 1, 'b': 2, 'c': 3}

swapped = {value: key for key, value in original.items()}
print(swapped)

{1: 'a', 2: 'b', 3: 'c'}


In [50]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_cubes = {num: num**3 for num in numbers if num % 2 == 0}
print(even_cubes)

{2: 8, 4: 64, 6: 216, 8: 512, 10: 1000}


In [51]:
keys = ['a', 'b', 'c', 'd', 'e']

values = [1, 2, 3, 4, 5]

new_dict = {key: value for key, value in zip(keys, values)}
print(new_dict)

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}


In [52]:
person = {
    'name': 'John',
    'age': 30,
    'contact': {
        'email': 'john@example.com',
        'phone': '123-456-7890'
    }
}

print(person['contact']['email'])

john@example.com


In [53]:
sentence = "Hello, world! Hello, Python!"
word_counts = {}

for word in sentence.split():
    if word in word_counts:
        word_counts[word] += 1
    else:
        word_counts[word] = 1

print(word_counts)

{'Hello,': 2, 'world!': 1, 'Python!': 1}


In [54]:
data = [
    {'name': 'John', 'age': 25, 'city': 'New York'},
    {'name': 'Jane', 'age': 30, 'city': 'Los Angeles'},
    {'name': 'Bob', 'age': 35, 'city': 'Chicago'}
]

filtered_data = [person for person in data if person['age'] > 30]
print(filtered_data)

[{'name': 'Bob', 'age': 35, 'city': 'Chicago'}]


In [55]:
list1 = [1, 2, 3, 4, 5]
list2 = [4, 5, 6, 7, 8]

set1 = set(list1)
set2 = set(list2)

common_elements = set1.intersection(set2)
print(common_elements)

elements = [1, 2, 3, 1, 2, 4, 5, 5]
unique_counts = {element: elements.count(element) for element in set(elements)}
print(unique_counts)

{4, 5}
{1: 2, 2: 2, 3: 1, 4: 1, 5: 2}


In [56]:
data = [
    {"name": "Alice", "age": 25, "city": "New York"},
    {"name": "Bob", "age": 30, "city": "Chicago"},
    {"name": "Charlie", "age": 35, "city": "New York"},
    {"name": "David", "age": 40, "city": "Chicago"}
]


grouped_data = {}
for person in data:
    city = person["city"]
    if city in grouped_data:
        grouped_data[city].append(person)
    else:
        grouped_data[city] = [person]

print(grouped_data)

{'New York': [{'name': 'Alice', 'age': 25, 'city': 'New York'}, {'name': 'Charlie', 'age': 35, 'city': 'New York'}], 'Chicago': [{'name': 'Bob', 'age': 30, 'city': 'Chicago'}, {'name': 'David', 'age': 40, 'city': 'Chicago'}]}


In [58]:
data = [
    {"name": "Alice", "age": 25, "city": "New York"},
    {"name": "Bob", "age": 30, "city": "Chicago"},
    {"name": "Charlie", "age": 35, "city": "New York"},
    {"name": "David", "age": 40, "city": "Chicago"}
]

# Filtering data based on age
filtered_data = [person for person in data if person["age"] > 30]

print(filtered_data)

[{'name': 'Charlie', 'age': 35, 'city': 'New York'}, {'name': 'David', 'age': 40, 'city': 'Chicago'}]


In [59]:
data = [
    {"name": "Alice", "age": 25, "city": "New York"},
    {"name": "Bob", "age": 30, "city": "Chicago"},
    {"name": "Charlie", "age": 35, "city": "New York"},
    {"name": "David", "age": 40, "city": "Chicago"}
]


city_ages = {}
for person in data:
    city = person["city"]
    age = person["age"]
    if city in city_ages:
        city_ages[city].append(age)
    else:
        city_ages[city] = [age]

average_ages = {city: sum(ages) / len(ages) for city, ages in city_ages.items()}

print(average_ages)

{'New York': 30.0, 'Chicago': 35.0}


In [60]:
sentence = "Hello, world! Hello, Python!"
word_counts = {}
for word in sentence.split():
    if word in word_counts:
        word_counts[word] += 1
    else:
        word_counts[word] = 1
print(word_counts)

{'Hello,': 2, 'world!': 1, 'Python!': 1}


In [61]:
config = {
    'database': {
        'host': 'localhost',
        'user': 'root',
        'password': 'secret'
    },
    'server': {
        'port': 8000,
        'enabled': True
    }
}
print(config['database'])
print(config['server'])

{'host': 'localhost', 'user': 'root', 'password': 'secret'}
{'port': 8000, 'enabled': True}


In [62]:
def merge_dicts(dict1, dict2):
    merged = dict1.copy()
    merged.update(dict2)
    return merged

dict1 = {'a': 1, 'b': 2}
dict2 = {'b': 3, 'c': 4}
merged_dict = merge_dicts(dict1, dict2)
print(merged_dict)

{'a': 1, 'b': 3, 'c': 4}


In [63]:
def sort_dict_by_value(dictionary):
    sorted_dict = dict(sorted(dictionary.items(), key=lambda x: x[1]))
    return sorted_dict

unsorted_dict = {'b': 2, 'a': 1, 'c': 3}
sorted_dict = sort_dict_by_value(unsorted_dict)
print(sorted_dict)

{'a': 1, 'b': 2, 'c': 3}


In [1]:
def remove_duplicate_values(dictionary):
    unique_values = {}
    for key, value in dictionary.items():
        if value not in unique_values.values():
            unique_values[key] = value
    return unique_values

original_dict = {'a': 1, 'b': 2, 'c': 1, 'd': 3, 'e': 2}
unique_dict = remove_duplicate_values(original_dict)
print(unique_dict)

{'a': 1, 'b': 2, 'd': 3}


In [2]:
def group_by_key(data, key):
    grouped = {}
    for item in data:
        value = item[key]
        if value in grouped:
            grouped[value].append(item)
        else:
            grouped[value] = [item]
    return grouped

data = [
    {'name': 'Alice', 'age': 25, 'city': 'New York'},
    {'name': 'Bob', 'age': 30, 'city': 'Chicago'},
    {'name': 'Charlie', 'age': 35, 'city': 'New York'},
    {'name': 'David', 'age': 40, 'city': 'Chicago'}
]

grouped_by_city = group_by_key(data, 'city')
print(grouped_by_city)

{'New York': [{'name': 'Alice', 'age': 25, 'city': 'New York'}, {'name': 'Charlie', 'age': 35, 'city': 'New York'}], 'Chicago': [{'name': 'Bob', 'age': 30, 'city': 'Chicago'}, {'name': 'David', 'age': 40, 'city': 'Chicago'}]}


### SETS

In [3]:
my_set = {1, 2, 3, 4, 5}

another_set = set([4, 5, 6, 7, 8])


print("Set created using '{}' curly brackets:",my_set)
print("Set created using set constructor:",another_set)

Set created using '{}' curly brackets: {1, 2, 3, 4, 5}
Set created using set constructor: {4, 5, 6, 7, 8}


In [4]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}
union_set = set1 | set2  # Output: {1, 2, 3, 4, 5}
print("Union:",union_set)

Union: {1, 2, 3, 4, 5}


In [5]:
grocery_list = {"apples", "bananas", "milk", "bread"}
household_list = {"detergent", "paper towels", "milk", "bread"}

shopping_list = grocery_list | household_list

print("Shopping list:",shopping_list)

Shopping list: {'bread', 'paper towels', 'apples', 'detergent', 'bananas', 'milk'}


In [6]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}
intersection_set = set1 & set2
print("Intersection:",intersection_set)

Intersection: {3}


In [7]:
hiking_group = {"hiking", "camping", "outdoors"}
photography_group = {"photography", "editing", "hiking"}

common_interests = hiking_group & photography_group

print("Common interests of both the group:",common_interests)

Common interests of both the group: {'hiking'}


In [8]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}
difference_set = set1 - set2
print("Difference:",difference_set)

Difference: {1, 2}


In [9]:
recommended_books = {"The Catcher in the Rye", "1984", "To Kill a Mockingbird", "Harry Potter"}
read_books = {"1984", "Harry Potter"}

unread_books = recommended_books - read_books

print("Books that already read:",unread_books)

Books that already read: {'To Kill a Mockingbird', 'The Catcher in the Rye'}


In [10]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}
symmetric_difference_set = set1 ^ set2
print("Symmetric Difference:",symmetric_difference_set)

Symmetric Difference: {1, 2, 4, 5}


In [11]:
restaurant1_menu = {"pizza", "pasta", "salad", "garlic bread"}
restaurant2_menu = {"pasta", "burger", "fries", "ice cream"}

unique_choices = restaurant1_menu ^ restaurant2_menu

print("Unique Dishes:",unique_choices)

Unique Dishes: {'pizza', 'fries', 'salad', 'ice cream', 'garlic bread', 'burger'}


In [12]:
my_set = {1, 2, 3}
print("Before add():",my_set)
my_set.add(4)
print("After add():",my_set)

Before add(): {1, 2, 3}
After add(): {1, 2, 3, 4}


In [13]:
my_set = {1, 2, 3}
print("Before remove():",my_set)
my_set.remove(2)
print("After remove():",my_set)

Before remove(): {1, 2, 3}
After remove(): {1, 3}


In [14]:
my_set = {1, 2, 3}
print("Before pop():",my_set)
removed_element = my_set.pop()
print("After pop():",removed_element)

Before pop(): {1, 2, 3}
After pop(): 1


In [15]:
my_set = {1, 2, 3}
print("Before clear():",my_set)
my_set.clear()
print("After clear():",my_set)

Before clear(): {1, 2, 3}
After clear(): set()


In [16]:
my_set = {1, 2, 3}
print("Before copy():",my_set)
copied_set = my_set.copy()
print("After copy():",copied_set)

Before copy(): {1, 2, 3}
After copy(): {1, 2, 3}


In [17]:
my_set = {1, 2, 3}
print("Before update():",my_set)
my_set.update([4, 5])
print("After update():",my_set)

Before update(): {1, 2, 3}
After update(): {1, 2, 3, 4, 5}


In [18]:
set1 = {1, 2}
set2 = {1, 2, 3, 4}
result = set1.issubset(set2)
print(result)

True


In [19]:
set1 = {1, 2, 3}
set2 = {4, 5, 6}
result = set1.isdisjoint(set2)
print(result)

True


In [20]:
my_set = {1, 2, 3, 4, 5}


print(3 in my_set)
print(6 in my_set)

True
False


In [21]:
squares = {x * x for x in range(1, 6)}
print(squares)

{1, 4, 9, 16, 25}


In [22]:
even_squares = {x * x for x in range(1, 6) if x % 2 == 0}
print(even_squares)

{16, 4}


In [23]:
user_interests = {
    'Alice': {'sports', 'music', 'reading'},
    'Bob': {'movies', 'music', 'gaming'},
    'Charlie': {'sports', 'music', 'cooking'},
    'David': {'sports', 'traveling', 'photography'},
    'Emma': {'music', 'reading', 'cooking'}
}

unique_interests = {interest for interests in user_interests.values() for interest in interests}

print("Unique Interests:",unique_interests)

Unique Interests: {'movies', 'traveling', 'sports', 'cooking', 'photography', 'gaming', 'music', 'reading'}


In [24]:
set1 = {1, 2}
set2 = {'a', 'b', 'c'}
cartesian_product = {(x, y) for x in set1 for y in set2}
print(cartesian_product)

{(2, 'b'), (2, 'a'), (2, 'c'), (1, 'b'), (1, 'a'), (1, 'c')}


In [25]:
def power_set(s):
    if len(s) == 0:
        return {frozenset()}
    element = s.pop()
    subsets = power_set(s)
    return subsets.union({subset.union({element}) for subset in subsets})

my_set = {1, 2, 3}
print(power_set(my_set))

{frozenset({2}), frozenset({2, 3}), frozenset({1, 2, 3}), frozenset({1, 2}), frozenset({3}), frozenset({1}), frozenset(), frozenset({1, 3})}


In [26]:
my_set = {1, 2, 3}
frozen_set = frozenset(my_set)
print(frozen_set)

frozenset({1, 2, 3})


In [ ]:
from sympy import BooleanAlgebra

ba = BooleanAlgebra()
set1 = {1, 2, 3}
set2 = {3, 4, 5}
intersection = ba.intersection(set1, set2)
print(intersection)


union = ba.union(set1, set2)
print(union)


complement = ba.complement(set1, set2)
print(complement)