<a href="https://colab.research.google.com/github/sharanya1234567/Sharanya-Vemula/blob/main/Python_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%pip install pandas
%pip install scipy

In [ ]:
import pandas as pd
df = pd.read_csv("loan_data.csv")
df.head()

credit.policy             purpose  int.rate  installment  log.annual.inc  \
0              1  debt_consolidation    0.1189       829.10       11.350407   
1              1         credit_card    0.1071       228.22       11.082143   
2              1  debt_consolidation    0.1357       366.86       10.373491   
3              1  debt_consolidation    0.1008       162.34       11.350407   
4              1         credit_card    0.1426       102.92       11.299732   

     dti  fico  days.with.cr.line  revol.bal  revol.util  inq.last.6mths  \
0  19.48   737        5639.958333      28854        52.1               0   
1  14.29   707        2760.000000      33623        76.7               0   
2  11.63   682        4710.000000       3511        25.6               1   
3   8.10   712        2699.958333      33667        73.2               1   
4  14.97   667        4066.000000       4740        39.5               0   

   delinq.2yrs  pub.rec  not.fully.paid  
0            0        0               0  
1            0        0               0  
2            0        0               0  
3            0        0               0  
4            1        0               0

In [ ]:
df.isnull()


credit.policy  purpose  int.rate  installment  log.annual.inc    dti  \
0             False    False     False        False           False  False   
1             False    False     False        False           False  False   
2             False    False     False        False           False  False   
3             False    False     False        False           False  False   
4             False    False     False        False           False  False   
...             ...      ...       ...          ...             ...    ...   
9573          False    False     False        False           False  False   
9574          False    False     False        False           False  False   
9575          False    False     False        False           False  False   
9576          False    False     False        False           False  False   
9577          False    False     False        False           False  False   

       fico  days.with.cr.line  revol.bal  revol.util  inq.last.6mths  \
0     False              False      False       False           False   
1     False              False      False       False           False   
2     False              False      False       False           False   
3     False              False      False       False           False   
4     False              False      False       False           False   
...     ...                ...        ...         ...             ...   
9573  False              False      False       False           False   
9574  False              False      False       False           False   
9575  False              False      False       False           False   
9576  False              False      False       False           False   
9577  False              False      False       False           False   

      delinq.2yrs  pub.rec  not.fully.paid  
0           False    False           False  
1           False    False           False  
2           False    False           False  
3           False    False           False  
4           False    False           False  
...           ...      ...             ...  
9573        False    False           False  
9574        False    False           False  
9575        False    False           False  
9576        False    False           False  
9577        False    False           False  

[9578 rows x 14 columns]

In [ ]:
df.isnull().sum()

credit.policy        0
purpose              0
int.rate             0
installment          0
log.annual.inc       0
dti                  0
fico                 0
days.with.cr.line    0
revol.bal            0
revol.util           0
inq.last.6mths       0
delinq.2yrs          0
pub.rec              0
not.fully.paid       0
dtype: int64

In [ ]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9578 entries, 0 to 9577
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   credit.policy      9578 non-null   int64  
 1   purpose            9578 non-null   object 
 2   int.rate           9578 non-null   float64
 3   installment        9578 non-null   float64
 4   log.annual.inc     9578 non-null   float64
 5   dti                9578 non-null   float64
 6   fico               9578 non-null   int64  
 7   days.with.cr.line  9578 non-null   float64
 8   revol.bal          9578 non-null   int64  
 9   revol.util         9578 non-null   float64
 10  inq.last.6mths     9578 non-null   int64  
 11  delinq.2yrs        9578 non-null   int64  
 12  pub.rec            9578 non-null   int64  
 13  not.fully.paid     9578 non-null   int64  
dtypes: float64(6), int64(7), object(1)
memory usage: 1.0+ MB


In [ ]:
df2 = df.fillna(value = 0)
df2.head()

credit.policy             purpose  int.rate  installment  log.annual.inc  \
0              1  debt_consolidation    0.1189       829.10       11.350407   
1              1         credit_card    0.1071       228.22       11.082143   
2              1  debt_consolidation    0.1357       366.86       10.373491   
3              1  debt_consolidation    0.1008       162.34       11.350407   
4              1         credit_card    0.1426       102.92       11.299732   

     dti  fico  days.with.cr.line  revol.bal  revol.util  inq.last.6mths  \
0  19.48   737        5639.958333      28854        52.1               0   
1  14.29   707        2760.000000      33623        76.7               0   
2  11.63   682        4710.000000       3511        25.6               1   
3   8.10   712        2699.958333      33667        73.2               1   
4  14.97   667        4066.000000       4740        39.5               0   

   delinq.2yrs  pub.rec  not.fully.paid  
0            0        0               0  
1            0        0               0  
2            0        0               0  
3            0        0               0  
4            1        0               0

In [ ]:
df3 = df.fillna(method='pad')
df3.head()

credit.policy             purpose  int.rate  installment  log.annual.inc  \
0              1  debt_consolidation    0.1189       829.10       11.350407   
1              1         credit_card    0.1071       228.22       11.082143   
2              1  debt_consolidation    0.1357       366.86       10.373491   
3              1  debt_consolidation    0.1008       162.34       11.350407   
4              1         credit_card    0.1426       102.92       11.299732   

     dti  fico  days.with.cr.line  revol.bal  revol.util  inq.last.6mths  \
0  19.48   737        5639.958333      28854        52.1               0   
1  14.29   707        2760.000000      33623        76.7               0   
2  11.63   682        4710.000000       3511        25.6               1   
3   8.10   712        2699.958333      33667        73.2               1   
4  14.97   667        4066.000000       4740        39.5               0   

   delinq.2yrs  pub.rec  not.fully.paid  
0            0        0               0  
1            0        0               0  
2            0        0               0  
3            0        0               0  
4            1        0               0

In [ ]:
df4 = df.fillna(value=df['installment'].mean())
df4

credit.policy             purpose  int.rate  installment  \
0                 1  debt_consolidation    0.1189       829.10   
1                 1         credit_card    0.1071       228.22   
2                 1  debt_consolidation    0.1357       366.86   
3                 1  debt_consolidation    0.1008       162.34   
4                 1         credit_card    0.1426       102.92   
...             ...                 ...       ...          ...   
9573              0           all_other    0.1461       344.76   
9574              0           all_other    0.1253       257.70   
9575              0  debt_consolidation    0.1071        97.81   
9576              0    home_improvement    0.1600       351.58   
9577              0  debt_consolidation    0.1392       853.43   

      log.annual.inc    dti  fico  days.with.cr.line  revol.bal  revol.util  \
0          11.350407  19.48   737        5639.958333      28854        52.1   
1          11.082143  14.29   707        2760.000000      33623        76.7   
2          10.373491  11.63   682        4710.000000       3511        25.6   
3          11.350407   8.10   712        2699.958333      33667        73.2   
4          11.299732  14.97   667        4066.000000       4740        39.5   
...              ...    ...   ...                ...        ...         ...   
9573       12.180755  10.39   672       10474.000000     215372        82.1   
9574       11.141862   0.21   722        4380.000000        184         1.1   
9575       10.596635  13.09   687        3450.041667      10036        82.9   
9576       10.819778  19.18   692        1800.000000          0         3.2   
9577       11.264464  16.28   732        4740.000000      37879        57.0   

      inq.last.6mths  delinq.2yrs  pub.rec  not.fully.paid  
0                  0            0        0               0  
1                  0            0        0               0  
2                  1            0        0               0  
3                  1            0        0               0  
4                  0            1        0               0  
...              ...          ...      ...             ...  
9573               2            0        0               1  
9574               5            0        0               1  
9575               8            0        0               1  
9576               5            0        0               1  
9577               6            0        0               1  

[9578 rows x 14 columns]

In [ ]:
df5 = df.dropna()
df5

credit.policy             purpose  int.rate  installment  \
0                 1  debt_consolidation    0.1189       829.10   
1                 1         credit_card    0.1071       228.22   
2                 1  debt_consolidation    0.1357       366.86   
3                 1  debt_consolidation    0.1008       162.34   
4                 1         credit_card    0.1426       102.92   
...             ...                 ...       ...          ...   
9573              0           all_other    0.1461       344.76   
9574              0           all_other    0.1253       257.70   
9575              0  debt_consolidation    0.1071        97.81   
9576              0    home_improvement    0.1600       351.58   
9577              0  debt_consolidation    0.1392       853.43   

      log.annual.inc    dti  fico  days.with.cr.line  revol.bal  revol.util  \
0          11.350407  19.48   737        5639.958333      28854        52.1   
1          11.082143  14.29   707        2760.000000      33623        76.7   
2          10.373491  11.63   682        4710.000000       3511        25.6   
3          11.350407   8.10   712        2699.958333      33667        73.2   
4          11.299732  14.97   667        4066.000000       4740        39.5   
...              ...    ...   ...                ...        ...         ...   
9573       12.180755  10.39   672       10474.000000     215372        82.1   
9574       11.141862   0.21   722        4380.000000        184         1.1   
9575       10.596635  13.09   687        3450.041667      10036        82.9   
9576       10.819778  19.18   692        1800.000000          0         3.2   
9577       11.264464  16.28   732        4740.000000      37879        57.0   

      inq.last.6mths  delinq.2yrs  pub.rec  not.fully.paid  
0                  0            0        0               0  
1                  0            0        0               0  
2                  1            0        0               0  
3                  1            0        0               0  
4                  0            1        0               0  
...              ...          ...      ...             ...  
9573               2            0        0               1  
9574               5            0        0               1  
9575               8            0        0               1  
9576               5            0        0               1  
9577               6            0        0               1  

[9578 rows x 14 columns]

In [ ]:
df6 = df.interpolate(method = 'linear')
df6

credit.policy             purpose  int.rate  installment  \
0                 1  debt_consolidation    0.1189       829.10   
1                 1         credit_card    0.1071       228.22   
2                 1  debt_consolidation    0.1357       366.86   
3                 1  debt_consolidation    0.1008       162.34   
4                 1         credit_card    0.1426       102.92   
...             ...                 ...       ...          ...   
9573              0           all_other    0.1461       344.76   
9574              0           all_other    0.1253       257.70   
9575              0  debt_consolidation    0.1071        97.81   
9576              0    home_improvement    0.1600       351.58   
9577              0  debt_consolidation    0.1392       853.43   

      log.annual.inc    dti  fico  days.with.cr.line  revol.bal  revol.util  \
0          11.350407  19.48   737        5639.958333      28854        52.1   
1          11.082143  14.29   707        2760.000000      33623        76.7   
2          10.373491  11.63   682        4710.000000       3511        25.6   
3          11.350407   8.10   712        2699.958333      33667        73.2   
4          11.299732  14.97   667        4066.000000       4740        39.5   
...              ...    ...   ...                ...        ...         ...   
9573       12.180755  10.39   672       10474.000000     215372        82.1   
9574       11.141862   0.21   722        4380.000000        184         1.1   
9575       10.596635  13.09   687        3450.041667      10036        82.9   
9576       10.819778  19.18   692        1800.000000          0         3.2   
9577       11.264464  16.28   732        4740.000000      37879        57.0   

      inq.last.6mths  delinq.2yrs  pub.rec  not.fully.paid  
0                  0            0        0               0  
1                  0            0        0               0  
2                  1            0        0               0  
3                  1            0        0               0  
4                  0            1        0               0  
...              ...          ...      ...             ...  
9573               2            0        0               1  
9574               5            0        0               1  
9575               8            0        0               1  
9576               5            0        0               1  
9577               6            0        0               1  

[9578 rows x 14 columns]

In [ ]:
import numpy as np
df7 = df.replace(to_replace= np.nan, value= 0)
df7

credit.policy             purpose  int.rate  installment  \
0                 1  debt_consolidation    0.1189       829.10   
1                 1         credit_card    0.1071       228.22   
2                 1  debt_consolidation    0.1357       366.86   
3                 1  debt_consolidation    0.1008       162.34   
4                 1         credit_card    0.1426       102.92   
...             ...                 ...       ...          ...   
9573              0           all_other    0.1461       344.76   
9574              0           all_other    0.1253       257.70   
9575              0  debt_consolidation    0.1071        97.81   
9576              0    home_improvement    0.1600       351.58   
9577              0  debt_consolidation    0.1392       853.43   

      log.annual.inc    dti  fico  days.with.cr.line  revol.bal  revol.util  \
0          11.350407  19.48   737        5639.958333      28854        52.1   
1          11.082143  14.29   707        2760.000000      33623        76.7   
2          10.373491  11.63   682        4710.000000       3511        25.6   
3          11.350407   8.10   712        2699.958333      33667        73.2   
4          11.299732  14.97   667        4066.000000       4740        39.5   
...              ...    ...   ...                ...        ...         ...   
9573       12.180755  10.39   672       10474.000000     215372        82.1   
9574       11.141862   0.21   722        4380.000000        184         1.1   
9575       10.596635  13.09   687        3450.041667      10036        82.9   
9576       10.819778  19.18   692        1800.000000          0         3.2   
9577       11.264464  16.28   732        4740.000000      37879        57.0   

      inq.last.6mths  delinq.2yrs  pub.rec  not.fully.paid  
0                  0            0        0               0  
1                  0            0        0               0  
2                  1            0        0               0  
3                  1            0        0               0  
4                  0            1        0               0  
...              ...          ...      ...             ...  
9573               2            0        0               1  
9574               5            0        0               1  
9575               8            0        0               1  
9576               5            0        0               1  
9577               6            0        0               1  

[9578 rows x 14 columns]

In [ ]:
#conditional statement
a = 10
b = 5

if a > b:
  print("a is greater than the b")
elif a < b:
  print("a is less than the b")
else:
  print("a is equal to b")

a is greater than the b


In [ ]:
fruits = ["apple", "banana", "cherry", "mango"]
for fruit in fruits:
    print(fruit)

count = 0
while count < 5:
    print(count)
    count += 1

apple
banana
cherry
mango
0
1
2
3
4


In [ ]:
fruits = ["apple", "cherry", "strwberry"]
print(len(fruits))
print(id(fruits))
print(type(fruits))
for i in range(5):
  print(i)

3
135937067813440
<class 'list'>
0
1
2
3
4


In [ ]:
class ParentClass:

    def prent_nethod(self):
        print("This parent method")

class ChildClass(ParentClass):

    def child_method(self):
        print("This is child method")

In [ ]:
class Animal:
  def make_sound(self):
    print("Generic animal sound")

class Dog(Animal):
  def make_sound(self):
    print("Woof!")

class Cat(Animal):
  def make_sound(self):
    print("Meow!")

class Poodle(Dog):  # Poodle inherits from Dog
  pass

animals = [Animal(), Dog(), Cat(), Poodle()]
for animal in animals:
  animal.make_sound()

Generic animal sound
Woof!
Meow!
Woof!


In [ ]:

class Parent:
    def func1(self):
        print("This function is in parent class.")




class Child(Parent):
    def func2(self):
        print("This function is in child class.")



object = Child()
object.func1()
object.func2()

This function is in parent class.
This function is in child class.


In [ ]:
class Mother:
    mothername = ""

    def mother(self):
        print(self.mothername)




class Father:
    fathername = ""

    def father(self):
        print(self.fathername)



class Son(Mother, Father):
    def parents(self):
        print("Father :", self.fathername)
        print("Mother :", self.mothername)


s1 = Son()
s1.fathername = "RAM"
s1.mothername = "SITA"
s1.parents()

Father : RAM
Mother : SITA


In [ ]:
# Base class
class Parent:
	def func1(self):
		print("This function is in parent class.")

# Derived class1
class Child1(Parent):
	def func2(self):
		print("This function is in child 1.")

# Derivied class2
class Child2(Parent):
	def func3(self):
		print("This function is in child 2.")


# Driver's code
object1 = Child1()
object2 = Child2()
object1.func1()
object1.func2()
object2.func1()
object2.func3()

This function is in parent class.
This function is in child 1.
This function is in parent class.
This function is in child 2.


In [ ]:
pip install numpy


In [ ]:
import numpy as np
print(np.__version__)

1.25.2


In [ ]:

a = np.array([1, 2, 3, 4, 5])
print(a.shape)

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)


c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c.shape)

(5,)
(2, 3)
(2, 2, 2)


In [ ]:
# Integer array
a = np.array([1, 2, 3, 4, 5])
print(a.dtype)

# Float array
b = np.array([1.0, 2.0, 3.0])
print(b.dtype)

# Complex array
c = np.array([1+2j, 3+4j])
print(c.dtype)

# Boolean array
d = np.array([True, False, True])
print(d.dtype)

int64
float64
complex128
bool


In [ ]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [ ]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a = np.empty(5)
print(a)


[4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323]


In [ ]:
a = np.linspace(0, 1, 5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
print(c)

[5 7 9]


In [ ]:
a = np.array([1, 4, 9])

b = np.sqrt(a)
print(b)

[1. 2. 3.]


In [ ]:
a = np.array([1, 2, 3])
b = 2
c = a + b
print(c)

[3 4 5]


In [ ]:
a = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 2, 4])
print(a[indices])

[1 3 5]


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a[2:6])
print(a[:4])
print(a[5:])
print(a[::2])
print(a[::-1])

[3 4 5 6]
[1 2 3 4]
[6 7 8 9]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1]


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a[::3])
print(a[::-2])

[1 4 7]
[9 7 5 3 1]


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)

# Reshape to a 2D array
b = a.reshape(2, 3)
print(b)

# Reshape to a 3D array
c = a.reshape(2, 1, 3)
print(c)

(6,)
[[1 2 3]
 [4 5 6]]
[[[1 2 3]]

 [[4 5 6]]]


In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])

# Stack arrays horizontally
c = np.hstack((a, b))
print(c)

# Stack arrays vertically
d = np.vstack((a, b))
print(d)

# Stack arrays along a new axis
e = np.stack((a, b), axis=1)
print(e)

[1 2 3 4]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [ ]:
a = np.array([1, 2, 3])
b = np.append(a, [4, 5])
print(b)

c = np.array([[1, 2], [3, 4]])
d = np.append(c, [[5, 6]], axis=0)
print(d)

[1 2 3 4 5]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.insert(a, 2, [10, 20])
print(b)

c = np.array([[1, 2], [3, 4]])
d = np.insert(c, 1, [10, 20], axis=1)
print(d)

[ 1  2 10 20  3  4  5]
[[ 1 10  2]
 [ 3 20  4]]


In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.delete(a, [0, 2])
print(b)

c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.delete(c, 1, axis=1)
print(d)

[2 4 5]
[[1 3]
 [4 6]]


In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.resize(a, (3, 3))
print(b)

[[1 2 3]
 [4 5 1]
 [2 3 4]]


In [ ]:
#Array Operations and Broadcasting:
#Given a 3D array a with shape (2, 3, 4) and a 2D array b with shape (3, 4), perform element-wise multiplication between a and b using broadcasting.


import numpy as np


a = np.random.rand(2, 3, 4)

b = np.random.rand(3, 4)

result = a * b
print(result)



In [ ]:
#Implement a function that takes two 2D arrays c and d with different shapes and performs element-wise operations (addition, subtraction, multiplication, and division) between them using broadcasting. Handle the case where broadcasting is not possible.

import numpy as np

def elementwise_operations(c, d):
    try:
        add = c + d
        print("Addition:\n", addition)


        sub = c - d
        print("Subtraction:\n", subtraction)


        mul = c * d
        print("Multiplication:\n", multiplication)


        div = c / d
        print("Division:\n", division)

    except ValueError as e:
        print("Error:", e)


c = np.random.rand(3, 4)
d = np.random.rand(1, 4)

elementwise_operations(c, d)


In [ ]:
#Create a 2D array e with shape (5, 3) and a 1D array f with length 5. Compute the outer product of e and f using broadcasting.#

import numpy as np

e = np.random.rand(5, 3)
f = np.random.rand(5)


outer_product = e * f[:, np.newaxis]

#
print("2D array", e)
print("1D array", f)
print("Outer product", outer_product)


In [ ]:
#Given a 3D array g with shape (4, 3, 2), extract every other element along the first and second dimensions, but keep all elements along the third dimension.

import numpy as np


g = np.random.rand(4, 3, 2)

result = g[::2, ::2, :]
print("Original array g:\n", g)
print("Extracted array:\n", result)


In [ ]:
#Create a function that takes a 2D array h and an array of row indices i and column indices j. The function should return a new array k where k[m, n] is the sum of the elements in h along the diagonal specified by i[m] and j[n].


import numpy as np

def diagonal_sum(h, i, j):

    k = np.zeros((len(i), len(j)))


    for m in range(len(i)):
        for n in range(len(j)):

            diag_indices = np.diag_indices(min(h.shape))
            k[m, n] = np.sum(h[i[m]:i[m]+1, j[n]:j[n]+1][diag_indices])

    return k


h = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

i = np.array([0, 1, 2])
j = np.array([0, 1, 2])

result = diagonal_sum(h, i, j)
print("Result:\n", result)



In [ ]:
#Implement a function that takes a 2D array l and returns a new array m where each element in m is the product of the corresponding row and column means in l.

import numpy as np

def row_column_means_product(l):

    row_means = np.mean(l, axis=1, keepdims=True)


    column_means = np.mean(l, axis=0, keepdims=True)


    m = row_means * column_means

    return m


l = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

result = row_column_means_product(l)
print("Result:\n", result)


In [ ]:
#Given a 2D array n with shape (4, 6), reshape it into a 3D array with shape (2, 2, 6) and then flatten it back to a 2D array with shape (4, 6).

import numpy as np


n = np.random.rand(4, 6)


reshaped_n = np.reshape(n, (2, 2, 6))


flattened_n = np.flatten(reshaped_n)

print("Original array shape:", n.shape)
print("Reshaped array shape:", reshaped_n.shape)
print("Flattened array shape:", flattened_n.shape)



In [ ]:
#Implement a function that takes a 2D array o and rolls it along the first axis by a specified number of positions. For example, if the input array is [[1, 2, 3], [4, 5, 6]] and the number of positions is 1, the output should be [[4, 5, 6], [1, 2, 3]].

import numpy as np

def roll_array_first_axis(o, positions):

    rolled_array = np.roll(o, positions, axis=0)
    return rolled_array


o = np.array([[1, 2, 3],
              [4, 5, 6]])

positions = 1
result = roll_array_first_axis(o, positions)
print("Original array:\n", o)
print("Rolled array:\n", result)


In [ ]:
#Create a function that takes a 2D array p and replaces all occurrences of a specified value x with the mean of the neighboring elements (horizontally and vertically) in the array.

import numpy as np

def replace_with_neighbor_mean(p, x):

    indices = np.where(p == x)


    for i, j in zip(indices[0], indices[1]):

        neighbor_mean = np.mean([
            p[i-1, j] if i > 0 else 0,
            p[i+1, j] if i < p.shape[0]-1 else 0,
            p[i, j-1] if j > 0 else 0,
            p[i, j+1] if j < p.shape[1]-1 else 0
        ])


        p[i, j] = neighbor_mean

    return p


p = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

x = 5
result = replace_with_neighbor_mean(p, x)
print("Result:\n", result)

